### ISSUE TITLE
Issue with recursivity in multiple places.

### ISSUE THREAD

**Issue by wael-jaber** [juanluispaz/ts-sql-query#57] opened 2022-11-23 11:34 UTC
You should wrap your recursive function call into a

- setTimeout,
- setImmediate
- process.nextTick

function to give node.js the chance to clear the stack. If you don't do that and there are many loops without any real async function call or if you do not wait for the callback, your RangeError: Maximum call stack size exceeded will be inevitable.

refer to this [stackoverflow post ](https://stackoverflow.com/questions/20936486/node-js-maximum-call-stack-size-exceeded).

I am dropping my usage for this lib unfortunately. since it has multiple issues which make it unreliable in real-world application

**Comment by juanluispaz** [comment] 2022-11-23 14:14
Can you give me more details on this?

We have several products midsize each one, monitored 24h, with very complex sql queries (not just CRUD), using this library in production and we never found something like you are describing here.

I'm preparing a release fixing the Sqlite issue you reported where the Date management need to be emulated due Sqlite doesn't have date type.

**Comment by juanluispaz** [comment] 2022-11-27 06:16
I'm going to close this due there is no way to reproduce it, and it never didn't show in our products that use the library.

When you get a "RangeError: Maximum call stack size exceeded will be inevitable." it is usually because you find yourself in an endless loop of function calls. In ts-sql-query that could be caused by misuse of the library, creating, for example, a circular loop of value source.

The case referred to in your link is a very specific (and very unusual) corner case of a pattern not present in ts-sql-query. But, if you search "RangeError: Maximum call stack size exceeded will be inevitable." in Google, a link to StackOverflow that you linked will be the first link to appear with the exact text you included here as the first answer.

Please review your situation in more detail before reporting a bug with the first answer in StackOverflow; and always provide a reproducible test case that allows the person to find the bug and fix it.

**Closed by juanluispaz** 2022-11-27 06:16 UTC
Labels: invalid
